openapi: 3.0.0
info:
  title: YOUR APP - API SPECS
  version: 0.0.1
  description: |
    Laboris sunt laborum ad eiusmod et ex irure aliquip laboris qui labore.
servers:
  - url: 'http://localhost:10001'
    description: "localhost"
tags:
  - name: "Authentication"
    description: ""
  - name: "Account"
    description: "Management user account"

paths:
  /config:
    get:
      tags:
        - "Misc"
      parameters:
        - in: query
          name: key
          required: false
          schema:
            type: string
      responses:
        200:
          description: "Ok"
  /file/upload:
    post:
      tags:
        - File
      summary: Upload file to server
      description: Upload file ini akan menghasilkan lokasi file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - type
                - format
              properties:
                type:
                  type: string
                  enum:
                    - temporary
                    - permanent
                  default: temporary
                format:
                  type: string
                  enum:
                    - images
                    - doc
                    - other
                  description: 'FORMAT : images: `jpg, png, jpeg`.  document: `(pdf, doc, xlsx, csv, xls)`. other: selain yang disebutkan tadi'
                file_group:
                  type: string
                  description: 'file group nya, contoh : avatar, kyc, community, dll'
                file:
                  type: string
                  format: binary
      responses:
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
  /auth/register:
    post:
      tags:
        - "Authentication"
      parameters:
        - $ref: "#/components/parameters/AppVersionParameter"
        - $ref: "#/components/parameters/AppPlatformParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
      responses:
        200:
         description: ""
  /auth/provider/google:
    post:
      tags:
       - "Authentication"
      description: ""
      requestBody:
        content:
          application/json:
            example:
              device:
                id: '123123'
                name: 'Xiaomi Note 11 Pro 5G'
                os: Android 12
                coordinate: 
                  long: '123123'
                  lat: '123123'
              provider:
                id:
                token:
      responses:
        200:
         description: ""
         content:
           application/json:
            schema:
              $ref: '#/components/schemas/AuthSuccessResponse'
  /auth/login:
    post:
      parameters:
        - $ref: "#/components/parameters/AppVersionParameter"
        - $ref: "#/components/parameters/AppPlatformParameter"
        - $ref: "#/components/parameters/AppLangParameter"
      tags:
        - "Authentication"
      description: |
        `identity` bisa di isi dengan username, email atau phone.
      requestBody:
        content:
          application/json:
            example:
              identity: john@doe.com
              password: password
              device:
                id: '123123'
                name: 'Xiaomi Note 11 Pro 5G'
                brand: 'Xiaomi'
                os: Android 12
              coordinate: 
                longitude: -6.4013011623988305
                latitude: 106.85269506615691
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
      responses:
        201:
         description: ""
         content:
           application/json:
            schema:
              $ref: '#/components/schemas/AuthSuccessResponse'
  /auth/refresh:
    post:
      security:
        - ApiKey: []
        - RefreshToken: []
      
      tags:
        - "Authentication"
      description: ""
      responses:
        200:
          description: "ok"
  /auth/logout:
    post:
      tags:
        - "Authentication"
      description: ""
      responses:
        200:
          description: "ok"
  /user:
    post:
      description: "Update Data User"
      security:
        - ApiKey: []
        - AuthToken: []
      tags:
        - "Account"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDataRequestBody'
            example:
              name: "John Doe"
              address: "Bogor, Indonesia"
              photo: "gs://user/photo/john-doe.jpg"
      responses:
        200:
          description: "ok"
    get:
      security:
        - ApiKey: []
        - AuthToken: []
      tags:
        - "Account"
      description: "Menampilkan detail informasi user"
      responses:
        200:
          description: "ok"
  /user/username-availability:
    get:
      description: "Cek ketersediaan username"
      summary: "Cek ketersediaan username"
      security:
        - ApiKey: []
        - AuthToken: []
      tags:
        - "Account"
      parameters:
        - name: username
          in: query
          schema:
            type: string
      responses:
        200:
          description: "Ok"
security:
  - ApiKey: []
  - AuthToken: []
components:
  responses:
    '401':
      description: 'This error probobly '
      content:
        application/json:
          example:
            status: UnAutorization
            message: Invalid access token
    '500':
      description: Internal server errors
      content:
        application/json:
          example:
            status: error
            message: This is the reason why
  parameters:
    AppVersionParameter:
      name: 'X-APP-VERSION'
      in: header
      required: true
      example: "1.0.0"
      schema:
        type: string
    AppPlatformParameter:
      name: 'X-APP-PLATFORM'
      in: header
      required: true
      example: "Android"
      schema:
        type: string
    AppLangParameter:
      name: 'X-APP-LANG'
      in: header
      required: true
      example: "en"
      schema:
        type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      description: "dev: `intervest-sandbox`"
      name: "x-api-key"
    AuthToken:
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
    RefreshToken:
      description: "Hanya dipakai di `/auth/refresh`"
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    LoginRequestBody:
      type: object
      properties:
        identity:
          type: string
          example: john@doe.com
          description: You can put email/username/phone
        password:
          type: string
        # provider:
        #   type: object
        #   description: |
        #     Paramter ini hanya dikirim padasaat melakukan autentikasi dengan 
        #     provider pihak ke 3 seperti google, facebook, twitter
        #   properties:
        #     name:
        #       type: string
        #       enum:
        #         - ["google", "facebook"]
        #     id:
        #       type: string
        #     token:
        #       type: string
        coordinate:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
        device:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            brand:
              type: string
            os:
              type: string
    AuthSuccessResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: object
          properties:
            tokens: 
              type: object
              description: "Authentication token (JWT) untuk di gunakan di endpoint terautentikasi."
              properties:
                access_token:
                  type: string
                  format: jwt
                refresh_token:
                  type: string
                  format: jwt
            user:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 12
                uuid:
                  type: string
                  format: uuid
                username:
                  type: string
                name:
                  type: string
                avatar:
                  type: string
                  nullable: true
                phone:
                  type: string
                phoneVerifiedAt:
                  type: string
                  format: date-time
                  nullable: true
                email:
                  type: string
                  format: email
                emailVerifiedAt:
                  type: string
                  format: date-time
                  nullable: true
                password:
                  type: string
                telegramAccount:
                  type: string
                  nullable: true
                telegramChatId:
                  type: string
                  nullable: true
                telegramVerifiedAt:
                  type: string
                  format: date-time
                  nullable: true
                memberId:
                  type: integer
                  format: int64
                memberPackageId:
                  type: integer
                  format: int64
                memberSubscriptionId:
                  type: integer
                  format: int64
                memberStatus:
                  type: string
                  nullable: true
    UpdateUserDataRequestBody:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        photo:
          type: string
    RegisterRequestBody:
      type: object
      properties:
        username:
          type: string
          example: "man.in.the.street"
        name:
          type: string
          description: "Full name"
          example: "Joe Blow"
        email:
          type: string
          example: "new1@mail.com"
        password:
          type: string
          example: "secret"
        phone:
          type: string
          example: +62857147333
        refferal_code:
          type: string
          example: ""
        coordinate:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
          example:
            longitude: -6.4013011623988305
            latitude: 106.85269506615691
        device:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            brand:
              type: string
            os:
              type: string
          example:
            id: '123123'
            name: 'Xiaomi Note 11 Pro 5G'
            brand: 'Xiaomi'
            os: Android 12