openapi: 3.0.0
info:
  title: INTERVEST.IO - API SPECS
  version: 0.0.1
servers:
  - url: 'http://localhost:10001'
    description: "localhost"
  - url: 'https://intervest.onbox.dev'
    description: "development"
paths:
  /auth/register:
    post:
      tags:
        - "Authentication"
      responses:
        200:
         description: ""
  /auth/login:
    post:
      tags:
        - "Authentication"
      requestBody:
        content:
          application/json:
            example:
              identity: john@doe.com
              password: password
              device:
                id: '123123'
                name: 'Xiaomi Note 11 Pro 5G'
                os: Android 12
                coordinate: 
                  long: '123123'
                  lat: '123123'
                provider:
                  name:
                  id:
                  token:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
      responses:
        200:
         description: ""
security:
  - ApiKey: []
  - AuthToken: []
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      description: "dev: `intervest-sandbox`"
      name: "x-api-key"
    AuthToken:
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    LoginRequestBody:
      type: object
      properties:
        identity:
          type: string
          example: john@doe.com
        password:
          type: string
        provider:
          type: object
          description: |
            Paramter ini hanya dikirim padasaat melakukan autentikasi dengan 
            provider pihak ke 3 seperti google, facebook, twitter
          properties:
            name:
              type: string
            id:
              type: string
            token:
              type: string
        device:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            os:
              type: string

    User:
      type: object
      properties:
        id:
          type: integer
